framework:
    rate_limiter:
        registration_attempts:
            policy: 'fixed_window'
            limit: 5
            interval: '24 hours'
        login_attempts:
            policy: 'fixed_window'
            limit: 10
            interval: '12 hours'
        trocarsenha_attempts:
            policy: 'fixed_window'
            limit: 5
            interval: '24 hours'
