when@prod:
  sentry:
  dsn: '%env(SENTRY_DSN)%'
  options:
    traces_sample_rate: 1.0
    profiles_sample_rate: 1.0
    ignore_exceptions:
      - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'
      - 'Symfony\Component\Messenger\Exception\RejectRedeliveredMessageException'
      - 'Symfony\Component\Security\Core\Exception\CustomUserMessageAuthenticationException'
